/*
 * build_sealane_correction.mjs
 *
 *   input   leip_sealane_correction.json  (per-leg geometry-based ratios)
 *   output  index.html  #leip-leg-correction  ratio table, upper triangle
 *
 * The ratio is symmetric by construction, so only one direction is stored
 * and the accessor normalises the key order. The table is the authority
 * for now; ENGINE.getLegCorrection is the single boundary, so when the
 * game computes the same quantity from its own sea lanes this block and
 * the accessor's body go together and nothing else moves.
 *
 *   node tools/build_sealane_correction.mjs [--write]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(join(ROOT, 'leip_sealane_correction.json'), 'utf8'));
const pack = JSON.parse(readFileSync(join(ROOT, 'leip_game_data.json'), 'utf8'));

const ports = pack.ports.map((p) => p.port).sort();
const ratio = src.ratio;

// --- integrity, reported loudly: a silent mismatch here would quietly
// --- mis-scale scoring distance for the affected legs.
const missing = ports.filter((p) => !ratio[p]);
if (missing.length) throw new Error(`no correction row for: ${missing.join(', ')}`);
const extra = Object.keys(ratio).filter((p) => !ports.includes(p));
if (extra.length) throw new Error(`correction rows for unknown ports: ${extra.join(', ')}`);

let asym = 0, pairs = 0, below1 = 0;
const vals = [];
for (let i = 0; i < ports.length; i++) {
  for (let j = i + 1; j < ports.length; j++) {
    const a = ports[i], b = ports[j];
    const ab = ratio[a][b], ba = ratio[b][a];
    if (ab === undefined || ba === undefined) throw new Error(`missing pair ${a}|${b}`);
    if (Math.abs(ab - ba) > 1e-9) asym++;
    if (ab < 1) below1++;
    vals.push(ab);
    pairs++;
  }
}
vals.sort((x, y) => x - y);
console.log(`${pairs} unordered pairs over ${ports.length} ports · ${asym} asymmetric · ${below1} below 1.0`);
console.log(`ratio min ${vals[0]} · median ${vals[Math.floor(vals.length / 2)]} · ` +
  `mean ${(vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(3)} · max ${vals[vals.length - 1]}`);

// The file also ships sea_nm. Where sea_nm disagrees with
// point-to-point x ratio, the file's own great-circle basis differs from
// the pack's distance matrix. We apply the ratio to the pack's matrix as
// instructed, so those legs land on the matrix's basis, not the file's.
if (src.sea_nm) {
  const m = pack.distance_matrix_nm;
  const off = [];
  for (let i = 0; i < ports.length; i++) {
    for (let j = i + 1; j < ports.length; j++) {
      const a = ports[i], b = ports[j];
      const pred = m[a][b] * ratio[a][b], obs = src.sea_nm[a][b];
      if (obs > 0 && Math.abs(pred - obs) / obs > 0.10) off.push({ a, b, pred, obs });
    }
  }
  off.sort((x, y) => Math.abs(y.pred - y.obs) / y.obs - Math.abs(x.pred - x.obs) / x.obs);
  console.log(`\n${off.length} pairs where matrix x ratio differs from the file's sea_nm by >10%:`);
  for (const o of off.slice(0, 8)) {
    console.log(`  ${o.a} <-> ${o.b}: matrix x ratio ${o.pred.toFixed(1)} nm vs sea_nm ${o.obs.toFixed(1)} nm`);
  }
  if (off.length > 8) console.log(`  (+${off.length - 8} more)`);
}

const CT = '<' + '/script>';
const rows = [];
for (let i = 0; i < ports.length; i++) {
  const a = ports[i];
  const cells = [];
  for (let j = i + 1; j < ports.length; j++) cells.push(`${JSON.stringify(ports[j])}:${ratio[a][ports[j]]}`);
  if (cells.length) rows.push(`    ${JSON.stringify(a)}: {${cells.join(',')}}`);
}

const block = `<script id="leip-leg-correction">
/* GENERATED by tools/build_sealane_correction.mjs — do not edit by hand.
   Source: leip_sealane_correction.json — ${src._stats.method}.
   Per-leg sea-lane correction: the factor by which the navigable distance
   between two ports exceeds the point-to-point distance. Symmetric, so
   only the upper triangle is stored; ENGINE.getLegCorrection normalises
   key order and is the ONLY reader. ${pairs} pairs, median ${src._stats.median}, max ${src._stats.max}.
   NOT encoded: traffic separation schemes, depth, local routing rules. */
globalThis.LEIP_LEG_CORRECTION = {
  stats: ${JSON.stringify(src._stats)},
  ratio: {
${rows.join(',\n')}
  }
};
${CT}`;

if (process.argv.includes('--write')) {
  const htmlPath = join(ROOT, 'index.html');
  let html = readFileSync(htmlPath, 'utf8');
  const re = /<script id="leip-leg-correction">[\s\S]*?<\/script>/;
  if (re.test(html)) html = html.replace(re, block);
  else html = html.replace('<script id="leip-data">', block + '\n\n<script id="leip-data">');
  writeFileSync(htmlPath, html);
  console.log(`\nwrote #leip-leg-correction (${(block.length / 1024).toFixed(0)} KB) into index.html`);
} else {
  console.log(`\n(dry run — pass --write; block is ${(block.length / 1024).toFixed(0)} KB)`);
}
